ext_sqd:
  amplitude_threshold: 0.003
  n_batches: 1
  num_cpus: 5
  recovery_iterations: 1
  # samples_per_batch: [50,100,200,300,500,600,1000,1500,2000,3000,5000]
  # samples_per_batch: [50,100,150,200,500,600,700,800,1000,1200,1500]
  samples_per_batch: [1,2,3,4,5,6,7,8,9,10]
  samples_per_batch_old: 27000
  sampling: hardware
  transitions: singles
max_davidson_cycles: 800
n_batches: 1
num_cpus: 80
parallelize_batches: false
recovery_iterations: 1
samples_per_batch: [10000,15000]
sampling: hardware
