ext_sqd:
  amplitude_threshold: 0.000019
  n_batches: 1
  num_cpus: 90
  recovery_iterations: 1
  samples_per_batch: [8]
  samples_per_batch_old: 20000
  sampling: hardware
  transitions: singles_and_doubles
max_davidson_cycles: 800
n_batches: 1
num_cpus: 5
parallelize_batches: false
recovery_iterations: 1
# samples_per_batch: [300,500,1000,2000,3000,4000,5000,6000,7000,8000]
samples_per_batch: [6000,7000,8000]
sampling: hardware
